### ISSUE TITLE
Implementar cambios de estado en el módulo de Cosido [1h]

### ISSUE THREAD

**Issue by diejavrom** [nacho270/GTLLiteClient#15]
En el módulo de Cosido al grabar "parcialmente" la primera vez debería dejar la ODT en "Por Comenzar" y luego al completar toda la info (botón ACEPTAR) debería cambiarla a estado "Finalizado".

**Comment by nacho270** [comment]
Tiempo: 1h.

**Comment by diejavrom** [comment]
revisar el método OrdenDeTrabajoFacade.grabarPiezasODT cuando se invoca desde el módulo de cosido porque genera transiciones por cada grabado parcial y debería generar solo 1 la primera vez (por comenzar) y otra al final en el aceptar (con estado "Finalizado").
