### ISSUE TITLE
Modulo de Cosido - ajuste en la lógica de localización de piezas [1,5h]

### ISSUE THREAD

**Issue by diejavrom** [nacho270/GTLLiteClient#17]
En el módulo de cosido se pide asignar el orden de las piezas ingresando los metros y asignar el siuiente orden a la primer pieza que coincide con la cantidad ingresada. Además agregar botones subir/bajar para intercambiar el orden de las piezas.

**Comment by nacho270** [comment]
Total: 1,5 hs
