### ISSUE TITLE
Módulo cosido - ajustes varios [30m]

### ISSUE THREAD

**Issue by diejavrom** [nacho270/GTLLiteClient#19]
En el módulo de asignación de órdenes a las piezas (Cosido) se piden hacer los siguientes ajustes:
1) arreglar la selección de la tabla cuando se hace con el teclado porque la habilitación de los botones subir/bajar no funciona del todo bien
2) agregar un scroll automático que posicione la tabla en la última fila encontrada
3) cambiar el texto del botón "imprimir" por "aceptar", se debe habilitar una vez que todas las piezas estén con orden. Al presionarlo debe imprimir.

**Comment by nacho270** [comment]
Total: 30m
