### ISSUE TITLE
Ajustes en la impresión de piezas [2h]

### ISSUE THREAD

**Issue by diejavrom** [nacho270/GTLLiteClient#8]
Hacer los siguientes ajustes en la impresión de la pieza:

- la medida de la hoja será de 10 (ancho) x 8 (alto) cm
- incorporar el logo
- incorporar: dirección, teléfono y mail de la empresa
- incorporar el nro de máquina desde donde se imprimió (ID del rasperry)	
- no se está imprimiendo la subpieza
- no se está imprimiendo la marca "#" que indica si es de 2da
- el producto no está incluyendo el proceso, imprime sólo "teñido" en vez de "teñido blanco óptico"
- quitar los primeros dígitos del año en el código de la ODT "2017*01*45" debería quedar "17*01*45"

**Comment by nacho270** [comment]
Agrego: 1,5h. Impresion de terminal, info de empresa, marca de agua. Terminal: hardcodeada. Falta subpieza.

**Comment by diejavrom** [comment]
Ya agregué lo de la subpieza. Falta solo lo de la terminal, por ahora dejo abierto el issue.

**Comment by nacho270** [comment]
Agregue terminal
